version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run:
          name: "Build TWRP"
          command: git clone https://github.com/akhilnarang/scripts && cd scripts && sudo bash setup/android_build_env.sh && cd .. && wget https://raw.githubusercontent.com/Exynos-nibba/twrp_device_samsung_a13/twrp-12.1/circle.sh && bash circle.sh
